### ISSUE TITLE
React warning: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by micaelmbagira** [asyncapi/markdown-template#104]
#### Describe the bug
Using the generator with the markdown template shows React warnings.

```
➜ npx ag https://bit.ly/asyncapi @asyncapi/markdown-template -o example

Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at Server (/test/asyncapi-bug/node_modules/@asyncapi/markdown-template/__transpiled/asyncapi.js:173:3)
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <Text>. See https://reactjs.org/link/warning-keys for more information.
    at Schema (/test/asyncapi-bug/node_modules/@asyncapi/markdown-template/__transpiled/asyncapi.js:257:3)


Done! ✨
Check out your shiny new generated files at /test/asyncapi-bug/example.
```
#### How to Reproduce
- `npx ag https://bit.ly/asyncapi @asyncapi/markdown-template -o example`

Or 

- `npm install @asyncapi/markdown-template`
- `npm install @asyncapi/generator`
- `npx ag https://bit.ly/asyncapi @asyncapi/markdown-template -o example`
 
#### Expected behavior
There should not be any error or warning.

**Comment by magicmatatjahu** [comment]
Problem is solved. Please use the latest version of `@asyncapi/generator: 1.7.2`:

```bash
npm i -g @asyncapi/generator
```
