### ISSUE TITLE
AsyncApi with custom avro type it fails to generate markdown-template

### ISSUE THREAD

**Issue by jyotibhangale** [asyncapi/markdown-template#239]
#### Describe the bug
When asyncapi have avro schemaFormat, if avro schema is complex schema, markdown template fails.
Complex schemas are defined in several files to be reused in different typed messages.
so if I have 

```
user_signedup.avsc:
{"namespace": "microcks.avro",
 "type": "record",
 "name": "UserSignedup",
 "fields": [
     {"name": "eventType", "type": "string"},
     {"name": "user",  "type": "microcks.avro.User"}
 ]
}
user.avsc:
{"namespace": "microcks.avro",
 "type": "record",
 "name": "User",
 "fields": [
     {"name": "name", "type": "string"},
     {"name": "user",  "type": "string"},
     {"name": "age", "type": "int"}
 ]
}
```

#### How to Reproduce
Define asyncapi with complex avro schemaFormat.

```
asyncapi: '2.0.0'
id: 'urn:io.microcks.example.user-signedup'
info:
  title: User signed-up Avro API
  version: 0.1.2
  description: Sample AsyncAPI for user signedup events defined using Avro
defaultContentType: application/json
channels:
  user/signedup:
    description: The topic on which user signed up events may be consumed
    subscribe:
      summary: Receive informations about user signed up
      operationId: receivedUserSIgnedUp
      message:
        description: An event describing that a user just signed up.
        bindings:
          kafka:
            key:
              type: string
              description: Timestamp of event as milliseconds since 1st Jan 1970
        traits:
          - $ref: '#/components/messageTraits/commonHeaders'
        headers:
          type: object
          properties:
            sentAt:
              type: string
              format: date-time
              description: Date and time when the event was sent
        contentType: avro/binary
        schemaFormat: application/vnd.apache.avro+json;version=1.9.0
        payload:
          $ref: './user-signedup.avsc#/User'
        examples:
          - laurent:
              summary: Example for Laurent user
              headers: |-
                {"my-app-header": 23, "sentAt": "2020-03-11T08:03:28Z"}
              payload: |-
                {"fullName": "Laurent Broudoux", "email": "laurent@microcks.io", "age": 41}
          - john:
              summary: Example for John Doe user
              headers:
                my-app-header: 24
                sentAt: "2020-03-11T08:03:38Z"
              payload:
                fullName: John Doe
                email: john@microcks.io
                age: 36
components:
  messageTraits:
    commonHeaders:
      headers:
        type: object
        properties:
          my-app-header:
            type: integer
            minimum: 0
            maximum: 100
      examples:
        laurent:
          my-app-header: 21
        yacine:
          my-app-header: 22

user_signedup.avsc:
{"namespace": "microcks.avro",
 "type": "record",
 "name": "UserSignedup",
 "fields": [
     {"name": "eventType", "type": "string"},
     {"name": "user",  "type": "microcks.avro.User"}
 ]
}
user.avsc:
{"namespace": "microcks.avro",
 "type": "record",
 "name": "User",
 "fields": [
     {"name": "name", "type": "string"},
     {"name": "user",  "type": "string"},
     {"name": "age", "type": "int"}
 ]
}
```

```
ag user-signedup.yml @asyncapi/markdown-template -o ../../api-docs/asyncapi -p outFilename=test.md --force-write
Something went wrong:
Error: Token "User" does not exist.
    at dereference (C:\Users\temp\AppData\Local\Yarn\Data\global\node_modules\@asyncapi\parser\lib\parser.js:159:11)
    at parse (C:\Users\temp\AppData\Local\Yarn\Data\global\node_modules\@asyncapi\parser\lib\parser.js:87:5)
    at Generator.generateFromString (C:\Users\temp\AppData\Local\Yarn\Data\global\node_modules\@asyncapi\generator\lib\generator.js:265:22)
    at C:\Users\temp\AppData\Local\Yarn\Data\global\node_modules\@asyncapi\generator\cli.js:154:9
```

#### Expected behavior
Generate markdown without any error.

**Comment by magicmatatjahu** [comment]
@jyotibhangale Hello! It's not related with `markdown-template` but with your invalid schema, because atm AsyncAPI resolves all references using syntax of JSON Reference, so you cannot use references like for AVSC files in AsyncAPI doc, but you should use only (in your case) `./user-signedup.avsc` to reference `User` model. You can read more here https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#referenceObject

Also if you think that something isn't working as expected please open issue in the avro-parser https://github.com/asyncapi/avro-schema-parser

**Comment by magicmatatjahu** [comment]
@jyotibhangale I close this one, if you think that there is problem (on the markdown-template side) please reopen, or create similar issue in the https://github.com/asyncapi/avro-schema-parser :)
