### ISSUE TITLE
TypeError: Cannot convert undefined or null to object after migrating from 0.19.8 to 1.0.0

### ISSUE THREAD

**Issue by Weinschenk** [asyncapi/markdown-template#251]
#### Describe the bug
After migrating from 0.19.8 to 1.0.0 the generation of the markdown broke with the exception: `TypeError: Cannot convert undefined or null`. Generation with 0.19.8 and the html Template (0.24.8) works.

#### How to Reproduce
I cannot provide the api (yml) because of a company policy. Nevertheless here is the stack trace:

```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Function.jsonFieldToSchema (/abc/node_modules/@asyncapi/markdown-template/helpers/schema.js:428:26)
    at reduce (/abc/node_modules/@asyncapi/markdown-template/helpers/schema.js:429:23)
    at Array.reduce (<anonymous>)
    at Function.jsonFieldToSchema (/abc/node_modules/@asyncapi/markdown-template/helpers/schema.js:428:41)
    at reduce (/abc/node_modules/@asyncapi/markdown-template/helpers/schema.js:429:23)
    at Array.reduce (<anonymous>)
    at Function.jsonFieldToSchema (/abc/node_modules/@asyncapi/markdown-template/helpers/schema.js:428:41)
    at Function.jsonToSchema (/abc/node_modules/@asyncapi/markdown-template/helpers/schema.js:400:23)
    at map (/abc/node_modules/@asyncapi/markdown-template/components/Bindings.js:14:36)
    at Array.map (<anonymous>)
    at Bindings (/abc/node_modules/@asyncapi/markdown-template/components/Bindings.js:12:51)
    at createElement (/abc/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:46:26)
    at /abc/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:70:26
    at Array.map (<anonymous>)
    at render (/abc/node_modules/@asyncapi/generator-react-sdk/src/renderer/renderer.ts:69:26)
error Command failed with exit code 1.
```

If this is not sufficient, I will try to anonymize the api. Just let me know...

#### Expected behavior
Template renders the api in markdown with 1.0.0. In case of a breaking chance, a migration guide is provided

**Comment by magicmatatjahu** [comment]
@Weinschenk Hi! Thanks for issue.

Could you tell me if your AsyncAPI spec has any `null`, `undefined` schema values, something like (probably in one of the bindings?):

```yaml
schema:
  someKey:
  anotherKey: null
```

I see that we don't cover such a case in the tests, so sorry for that. I will create PR for that as soon as possible.

> In case of a breaking chance, a migration guide is provided

Template "hasn't" breaking changes, just a more accurate rendering, but we might have forgotten about some case that has broken with current template.

**Comment by magicmatatjahu** [comment]
Fix is on the way -> https://github.com/asyncapi/markdown-template/pull/252

**Comment by Weinschenk** [comment]
Works perfectly fine. Thanks a lot
