### ISSUE TITLE
Markdown: Vertical bars not "escaped" within tables.

### ISSUE THREAD

**Issue by rcollette** [asyncapi/markdown-template#292]
#### Describe the bug
Given content that includes vertical bars, such as regular expressions, when rendered in a markdown table cell, the vertical bars in the content are not escaped (ex. using HTML escape characters)

#### How to Reproduce

```yml
asyncapi: 2.4.0
id: urn:com
info:
  title: title
  version: 1.0.0
defaultContentType: application/json
channels:
  topic:
    publish:
      operationId: publishEvent
      message:
        name: event
        payload:
          $ref: "#/components/schemas/schema"
components:
  schemas:
    schema:
      type: object
      required:
        - eventStart
      properties:
        eventStart:
          type: string
          description: ISO8601 UTC date-time string using Z zone designator
          format: date-time
          # Regex Modified to remove zone offset designators from https://stackoverflow.com/a/43931246/107683
          pattern: ^(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d{1,9})?(?:Z)$
   ```
#### Expected behavior
The vertical bars that are part of table cell content need to be "escaped", probably by using HTML encoding within a `<code>`block.
https://stackoverflow.com/a/43591562/107683

**Comment by magicmatatjahu** [comment]
@rcollette Sorry for such a delay! Where do you render output, because in Visual Studio Code and in Github it renders to the:

| Name | Type | Description | Value | Constraints | Notes |
|---|---|---|---|---|---|
| (root) | object | - | - | - | **additional properties are allowed** |
| eventStart | string | ISO8601 UTC date-time string using Z zone designator | - | format (`date-time`), pattern (`^(?:[1-9]\d{3}-(?:(?:0[1-9]\|1[0-2])-(?:0[1-9]\|1\d\|2[0-8])\|(?:0[13-9]\|1[0-2])-(?:29\|30)\|(?:0[13578]\|1[02])-31)\|(?:[1-9]\d(?:0[48]\|[2468][048]\|[13579][26])\|(?:[2468][048]\|[13579][26])00)-02-29)T(?:[01]\d\|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d{1,9})?(?:Z)$`) | **required** |

I need more info to test behaviour.

**Comment by rcollette** [comment]
I was using the following npm scripts to build.

```json
```

**Comment by rcollette** [comment]
I was using the following npm scripts to build.

```json
{
  "name": "consumption",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build:markdown": "ag ./consumption-asyncapi.yml @asyncapi/markdown-template",
    "watch:markdown": "ag --watch-template --force-write ./consumption-asyncapi.yml @asyncapi/markdown-template",
template"
  },
  "author": "Richard Collette <richard.collette@precisely.com>",
  "license": "ISC",
  "devDependencies": {
    "@asyncapi/generator": "^1.9.5",
    "@asyncapi/markdown-template": "^1.1.2"
  }
}
```

**Comment by rcollette** [comment]
I just tried to run it again with the latest versions and I'm getting an error :(

```bash
MacBook-Pro-3:consumption Richard.Collette$ ag ./consumption-asyncapi.yml @asyncapi/markdown-template
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module './yamlAST'
Require stack:
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/yaml-ast-parser/dist/src/loader.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/yaml-ast-parser/dist/src/index.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@fmvilas/pseudo-yaml-ast/src/index.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/utils.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/customValidators.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/parser.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/index.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/generator/lib/generator.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/generator/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/yaml-ast-parser/dist/src/loader.js:3:11)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/yaml-ast-parser/dist/src/loader.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/yaml-ast-parser/dist/src/index.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@fmvilas/pseudo-yaml-ast/src/index.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/utils.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/customValidators.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/parser.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/index.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/generator/lib/generator.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/generator/cli.js'
  ]
}

```

**Comment by magicmatatjahu** [comment]
@rcollette Thanks! Could you try with:

```bash
npx @asyncapi/generator@1.9.11 ./sample.yaml @asyncapi/markdown-template -o ./sample --force-write
```

? Please check if global `ag` points to the `1.9.11` version by `ag --version`. 

In my question I meant in which environment do you use the generated documentation, on Gitlab or where? This is important because we cannot use html in the generated documentation because not all Markdown syntaxes support html - we had an issue with this in the past.

**Comment by rcollette** [comment]
Ugh. I think I notice what happened now.

The Jetbrains editor, at least at one point, formatted the md, but didn't recognized the \ escaped pipes as escaped pipes and wound up inserting spaces to attempt to align table columns.

![image](https://user-images.githubusercontent.com/136476/192808739-6385744a-1b22-4e4a-ae90-1c418dfb69f7.png)

After fixing that, my current version of Webstorm seems to leave the formatting alone (even if I reformat the document), but their renderer doesn't recognized escaped pipes as such
![image](https://user-images.githubusercontent.com/136476/192810202-20a246bb-81a5-416b-9637-0ed92d1f2240.png)


Confluence doesn't treat the escaped pipes as table pipes, but it also renders the escape character
![image](https://user-images.githubusercontent.com/136476/192809606-1ed54b27-ebe5-44f4-a2c7-e0ba55b0c63d.png)

So in terms of pipes, this is all a bunch of formatter/renderer issues.

Still having an issue running 1.9.11 though.
```bash
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
MacBook-Pro-3:consumption Richard.Collette$ nvm use
Found '/Users/Richard.Collette/Documents/code/onboarding/consumption/.nvmrc' with version <16.17.0>
Now using node v16.17.0 (npm v8.15.0)
MacBook-Pro-3:consumption Richard.Collette$ ag --version
1.9.11
MacBook-Pro-3:consumption Richard.Collette$ npx @asyncapi/generator@1.9.11 ./consumption-asyncapi.yml @asyncapi/markdown-template --force-write
Need to install the following packages:
  @asyncapi/generator@1.9.11
Ok to proceed? (y) y
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module './yamlAST'
Require stack:
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/yaml-ast-parser/dist/src/loader.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/yaml-ast-parser/dist/src/index.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@fmvilas/pseudo-yaml-ast/src/index.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/utils.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/customValidators.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/parser.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/index.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/generator/lib/generator.js
- /Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/generator/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/yaml-ast-parser/dist/src/loader.js:3:11)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/yaml-ast-parser/dist/src/loader.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/yaml-ast-parser/dist/src/index.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@fmvilas/pseudo-yaml-ast/src/index.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/utils.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/customValidators.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/parser.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/parser/lib/index.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/generator/lib/generator.js',
    '/Users/Richard.Collette/Documents/code/onboarding/consumption/node_modules/@asyncapi/generator/cli.js'
  ]
}
```

**Comment by magicmatatjahu** [comment]
@rcollette Thanks for that! So as I see we have a lot of problems related to given env where markdown is rendered. As I wrote we cannot use html tags (by default), but we can use them with passing template parameter something like `--with-html` and by this we can escape pipes with your suggestion https://stackoverflow.com/questions/43591484/github-vs-npm-markdown-escaping-vertical-bar/43591562#43591562 I will start doing this tomorrow, but if I could have a request to you, could you create issue in the repository https://github.com/asyncapi/generator, because as I see it is a problem on the side of the generator itself and not the template.
